//! One tiny route: open the pantheon "New Model, New Project" LLM-leaderboard HTML page in the
//! operator's default browser. The page itself is generated by `pantheon/scripts/score-episode.ps1`
//! and lives alongside the series hub; dotz only needs to open it.

use axum::{Json, Router, routing::post};
use serde_json::{Value, json};
use std::path::{Path, PathBuf};

/// Resolve `pantheon/leaderboard.html`. Override with `DOTZ_LEADERBOARD_HTML`; otherwise derive it
/// from the build location: `<...>/projects/dotz/dotz-core` → `<...>/projects/pantheon/leaderboard.html`.
fn leaderboard_path() -> PathBuf {
    if let Ok(p) = std::env::var("DOTZ_LEADERBOARD_HTML")
        && !p.trim().is_empty()
    {
        return PathBuf::from(p);
    }
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent() // .../projects/dotz
        .and_then(|p| p.parent()) // .../projects
        .map(|projects| projects.join("pantheon").join("leaderboard.html"))
        .unwrap_or_else(|| PathBuf::from("pantheon/leaderboard.html"))
}

/// POST /api/leaderboard/open -> { ok, path } — launches the leaderboard page with its default handler.
async fn open_leaderboard() -> Json<Value> {
    let path = leaderboard_path();
    if !path.exists() {
        return Json(json!({
            "ok": false,
            "error": format!("leaderboard page not found at {}", path.display())
        }));
    }
    let ok = open_default(&path);
    Json(json!({ "ok": ok, "path": path.to_string_lossy() }))
}

#[cfg(windows)]
fn open_default(path: &Path) -> bool {
    use std::os::windows::process::CommandExt;
    const CREATE_NO_WINDOW: u32 = 0x0800_0000; // no console flash (house convention)
    // `cmd /c start "" "<path>"` opens the file with its registered handler (browser for .html).
    std::process::Command::new("cmd")
        .args(["/c", "start", ""])
        .arg(path)
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
        .is_ok()
}

#[cfg(not(windows))]
fn open_default(path: &Path) -> bool {
    std::process::Command::new("xdg-open")
        .arg(path)
        .spawn()
        .is_ok()
}

pub fn router() -> Router<()> {
    Router::new().route("/api/leaderboard/open", post(open_leaderboard))
}
